name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.4.2'
        arch: 'win64_mingw'
        tools: 'tools_mingw90'
        
    - name: Check Environment
      run: |
        g++ --version
        cmake --version
        ninja --version
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        windeployqt --release --qmldir ../src/ui appOpenIPC-Dashboard.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenIPC-Dashboard-Windows
        path: |
          build/appOpenIPC-Dashboard.exe
          build/*.dll
          build/plugins/
          build/qml/
          build/translations/
