# .github/workflows/release.yml

name: Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # --- [БЛОК 1] Сборка исполняемого файла аналитики ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Упрощенная и унифицированная установка зависимостей
      - name: Install Python dependencies
        run: pip install -r python_requirements.txt

      # ИЗМЕНЕННАЯ КОМАНДА СБОРКИ: Используем .spec файл
      - name: Build analytics executable
        run: pyinstaller python_src/analytics.spec --distpath extra/analytics --workpath build_pyinstaller

      # --- [БЛОК 2] Сборка Electron-приложения ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfuse2
      
      - name: Build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist -- --publish always