name: Build & Release

# Запускать этот workflow при пуше тега, который начинается с 'v' (например, v1.0.0)
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    # Запускать на последней версии Windows (так как мы собираем .exe)
    # Для сборки под macOS или Linux нужно использовать 'macos-latest' или 'ubuntu-latest'
    runs-on: windows-latest

    steps:
      # 1. Получаем исходный код из репозитория
      - name: Check out git repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Укажите версию Node.js, которую вы используете
          cache: 'npm'

      # 3. Устанавливаем зависимости проекта
      - name: Install dependencies
        run: npm install

      # 4. Собираем и публикуем приложение
      - name: Build and release
        # Используем секретный токен, который мы создали
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist -- --publish always