# .github/workflows/release.yml

name: Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      # --- [БЛОК 1] Сборка исполняемого файла аналитики ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # УЛУЧШЕНИЕ: Добавлено кэширование pip

      - name: Install Python dependencies
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          else
            pip install torch torchvision
          fi
          pip install ultralytics pyinstaller

      - name: Build analytics executable
        run: python -m PyInstaller --onefile python_src/analytics.py --distpath extra/analytics --name analytics

      # --- [БЛОК 2] Сборка Electron-приложения ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfuse2
      
      - name: Build and release Electron app
        env:
          # ИСПРАВЛЕНО: Используем стандартный GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            FUSE_SYMLINK="/usr/lib/x86_64-linux-gnu/libfuse.so.2"
            if [ ! -f "$FUSE_SYMLINK" ]; then
               echo "::error::Symlink for libfuse.so.2 not found at $FUSE_SYMLINK"
               exit 1
            fi
            FUSE_PATH=$(readlink -f $FUSE_SYMLINK)
            
            # УЛУЧШЕНИЕ: Проверка, что библиотека найдена
            if [ -z "$FUSE_PATH" ] || [ ! -f "$FUSE_PATH" ]; then
              echo "::error::Could not resolve real path for libfuse.so.2"
              exit 1
            fi

            echo "FUSE library found at: $FUSE_PATH"
            EXTRA_FILES_CONFIG='[{"from": "'"$FUSE_PATH"'", "to": "lib/libfuse.so.2"}]'
            npm run dist -- --publish always --config.linux.extraFiles="$EXTRA_FILES_CONFIG"
          else
            npm run dist -- --publish always
          fi